---
- name: Create working directory
  ansible.builtin.file:
    group: "{{ powerdns_auth_proxy_group }}"
    owner: "{{ powerdns_auth_proxy_user }}"
    path: "{{ powerdns_auth_proxy_work_path }}"
    state: 'directory'

- ansible.builtin.include_tasks: "download/{{ powerdns_auth_proxy_download_method }}.yml"

- ansible.builtin.include_tasks: install.yml

- ansible.builtin.include_tasks: configuration.yml

- ansible.builtin.include_tasks: services.yml
